export function initUsers() {
  const users = [
    {
      "_id" : "65edbf9c5f5fc38e6b0aec80",
      "firstName" : "Tiffany",
      "lastName" : "Chu",
      "gender": "Female",
      "email" : "cltchu@shkp.com",
      "phone": "+852 98765432",
      "organization": "Sanfield (Management) Limited",
      "department": "IT",
      "jobTitle": "Project Manager",
      "username": "tiffanychu",
      "password" : "$2b$10$k0d6Q96zypbGzN2ZpW.dEeCunvGvNEcyjs69r0slx5oTwWgpJu2Vq",
      "active": true,
    },
    {
      "_id" : "65ed2f85b407f3000d2f6373",
      "firstName" : "Bubbles",
      "lastName" : "Chu",
      "gender": "Female",
      "email" : "bubbleschu@hotmail.com.hk",
      "phone": "+852 12345678",
      "organization": "Sanfield (Management) Limited",
      "department": "IT",
      "jobTitle": "Project Manager",
      "username": "bubbleschu",
      "password" : "$2b$10$dPO8ohjIbEnmoJD//8Mz6uy5gBhlBTTOdHxWIboo76U4jv3lHrdly",
      "active": true,
    },
    {
    "_id" : "65f55a9bf14fff03ba585f3b",
      "firstName" : "振",
      "lastName" : "明",
      "gender": "Male",
      "email" : "zmlin@shkp.com",
      "phone": "+852 23456789",
      "organization": "Sanfield (Management) Limited",
      "department": "IT",
      "jobTitle": "Frontend Developer",
      "username": "zhenming",
      "password" : "$2b$10$k0d6Q96zypbGzN2ZpW.dEeCunvGvNEcyjs69r0slx5oTwWgpJu2Vq",
      "active": true,
    },
    {
      "_id" : "65f55a9bf14fff03ba585f3c",
      "firstName": "燁",
      "lastName": "鳴",
      "gender": "Male",
      "email": "ymluo@shkp.com",
      "phone": "+852 34567891",
      "organization": "Sanfield (Management) Limited",
      "department": "IT",
      "jobTitle": "Frontend Developer",
      "username": "yeming",
      "password": "$2b$10$k0d6Q96zypbGzN2ZpW.dEeCunvGvNEcyjs69r0slx5oTwWgpJu2Vq",
      "active": true,
    },
    {
      "_id" : "65f55a9bf14fff03ba585f3d",
      "firstName": "浩",
      "lastName": "傑",
      "gender": "Male",
      "email": "hjliang@shkp.com",
      "phone": "+852 45678912",
      "organization": "Sanfield (Management) Limited",
      "department": "IT",
      "jobTitle": "Backend Developer",
      "username": "haojie",
      "password": "$2b$10$k0d6Q96zypbGzN2ZpW.dEeCunvGvNEcyjs69r0slx5oTwWgpJu2Vq",
      "active": true,
    },
    {
      "_id" : "65f55a9bf14fff03ba585f3e",
      "firstName": "啟",
      "lastName": "明",
      "gender": "Male",
      "email": "qmxiao@shkp.com",
      "phone": "+852 56789123",
      "organization": "Sanfield (Management) Limited",
      "department": "IT",
      "jobTitle": "Fullstack Developer",
      "username": "qiming",
      "password": "$2b$10$k0d6Q96zypbGzN2ZpW.dEeCunvGvNEcyjs69r0slx5oTwWgpJu2Vq",
      "active": true,
    },
    {
      "_id" : "65f55a9bf14fff03ba585f3f",
      "firstName": "維",
      "lastName": "飛",
      "gender": "Male",
      "email": "wfhuang@shkp.com",
      "phone": "+852 67891234",
      "organization": "Sanfield (Management) Limited",
      "department": "IT",
      "jobTitle": "Fullstack Developer",
      "username": "weifei",
      "password": "$2b$10$k0d6Q96zypbGzN2ZpW.dEeCunvGvNEcyjs69r0slx5oTwWgpJu2Vq",
      "active": true,
    },
    {
      "_id" : "65f55a9bf14fff03ba585f40",
      "firstName": "陳",
      "lastName": "慶",
      "gender": "Male",
      "email": "qchen@shkp.com",
      "phone": "+852 78912345",
      "organization": "Sanfield (Management) Limited",
      "department": "IT",
      "jobTitle": "Backend Developer",
      "username": "chenqing",
      "password": "$2b$10$k0d6Q96zypbGzN2ZpW.dEeCunvGvNEcyjs69r0slx5oTwWgpJu2Vq",
      "active": true,
    },
    {
      "_id" : "65f55d4af14fff03ba585f42",
      "firstName" : "海",
      "lastName" : "輝",
      "gender": "Male",
      "email" : "hhlan@shkp.com",
      "phone": "+852 89123456",
      "organization": "Sanfield (Management) Limited",
      "department": "IT",
      "jobTitle": "Backend Developer",
      "username": "haihui",
      "password" : "$2b$10$k0d6Q96zypbGzN2ZpW.dEeCunvGvNEcyjs69r0slx5oTwWgpJu2Vq",
      "active": true,
    },
    {
      "_id" : "65f55d4af14fff03ba585f41",
      "firstName" : "劉",
      "lastName" : "汶",
      "gender": "Male",
      "email" : "wliu@shkp.com",
      "phone": "+852 91234567",
      "organization": "Sanfield (Management) Limited",
      "department": "IT",
      "jobTitle": "Frontend Developer",
      "username": "liuwen",
      "password" : "$2b$10$k0d6Q96zypbGzN2ZpW.dEeCunvGvNEcyjs69r0slx5oTwWgpJu2Vq",
      "active": true,
    }
  ];

  return users;
}
